[package]
name = "rust-chibi-protocol-stack"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
num_enum = "0.7.2"
once_cell = "1.19.0"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "sync"] }
tun = "0.6.1"
